# Generated by Django 4.2.5 on 2023-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(default='qwert', upload_to='pics'),
            preserve_default=False,
        ),
    ]
